#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
pushd $HOME/.dotfiles
for folder in $(exa -1)
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
