#!/usr/bin/env zsh

pushd $DOTFILES
for dir in $(find . -mindepth 1 -maxdepth 1 -type d | sed "s|./||" | grep -v install | grep -v '.git')
do
    echo "stow $dir"
    stow -D $dir
    stow $dir
done
popd
