general {
    col.active_border = rgba(#271016ff) rgba(#C36548ff) 45deg
    col.inactive_border = rgba(#592524cc) rgba(#F9D7BDcc) 45deg
    col.group_border_active = rgba(#271016ff) rgba(#C36548ff) 45deg
    col.group_border = rgba(#592524cc) rgba(#F9D7BDcc) 45deg
    col.group_border_locked_active = rgba(#271016ff) rgba(#C36548ff) 45deg
    col.group_border_locked = rgba(#592524cc) rgba(#F9D7BDcc) 45deg
}
