github.com:
    user: llComodino
    git_protocol: https
    oauth_token: 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
    users:
        llComodino:
            oauth_token: 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
