;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = ${xrdb:color0}
foreground = ${xrdb:color}
primary = ${xrdb:color1}
secondary = ${xrdb:color5}
alert = ${xrdb:color6}

[bar/bar_top]
monitor = ${env:MONITOR:}
width = 100%
height = 40
fixed-center = true
enable-ipc = true
tray-position = right

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 6
line-color = #f00

padding-left = 1
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = Blexmono Nerd Font:size=18
font-1 = Gen Jyuu Gothic Monospace Regular:size=18

modules-left = pulseaudio padding memory cpu padding power-profile
modules-center = spotify
modules-right = date padding battery padding

cursor-click = pointer
cursor-scroll = ns-resize

[bar/bar_bottom]
monitor = ${env:MONITOR:}
width = 100%
height = 40
fixed-center = true

bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 6
line-color = #f00

padding-left = 1
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = Blexmono Nerd Font:size=14

modules-left = filesystem
modules-center = i3
modules-right = wired-network wireless-network

cursor-click = pointer
cursor-scroll = ns-resize

[module/filesystem]
type = internal/fs
interval = 30

mount-0 = /
mount-1 = /home
mount-2 = /boot

format-mounted = <label-mounted>
format-unmounted = ""
label-mounted = %mountpoint%: %percentage_used%%

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = ${colors.foreground}
label-mode-background = ${xrdb:color0}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-underline= ${xrdb:color1}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-underline= ${xrdb:color3}
label-unfocused-padding = 2

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-underline= ${xrdb:color2}
label-visible-padding = 2

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${xrdb:color2}
label = %percentage%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = "󰓅 "
format-prefix-foreground = ${xrdb:color2}
label = %percentage_used%%

[module/date]
type = internal/date
interval = 1

date = "%d.%m.%Y"

time = "%H:%M:%S"

label = %time% - %date%

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume>
label-volume = %percentage%%

format-volume-prefix = " "
format-volume-prefix-foreground = ${xrdb:color2}

label-muted = muted
label-muted-foreground = #666

format-muted-prefix = " "
format-muted-prefix-foreground = ${xrdb:color2}

[settings]
screenchange-reload = true

[module/spotify]
type = custom/script
tail = true
interval = 1
format-prefix = " "
format = <label>
content-font = 1
label-maxlen = 40
exec = $HOME/.config/polybar/scripts/get_spotify_status.sh
scroll-down = playerctl volume 0.1+ -p spotify
scroll-up = playerctl volume 0.1- -p spotify
click-left = playerctl play-pause -p spotify
click-right = playerctl next -p spotify
click-middle = playerctl previous -p spotify

[module/wired-network]
type = internal/network
interface = enp7s0f4u1

interval = 3.0

accumulate-stats = false
unknown-as-up = true

; speed-unit = 

; Available tags:
;   <label-connected> (default)
;   <ramp-signal>
format-connected = <ramp-signal> <label-connected>

; Available tags:
;   <label-disconnected> (default)
format-disconnected = <label-disconnected>

; All labels support the following tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %netspeed%  [wireless+wired] (%upspeed% + %downspeed%) (New in version 3.6.0)
;   %linkspeed% [wired]
;   %mac%       [wireless+wired] (New in version 3.6.0)

; Default: %ifname% %local_ip%
label-connected = %local_ip%  :  %upspeed:50% %downspeed:9%
label-connected-foreground = #eefafa

; Default: (none)
label-disconnected = ''
label-disconnected-foreground = #66ffff

; Default: (none)
;label-packetloss = %essid%
;label-packetloss-foreground = #eefafafa

; Only applies if <ramp-signal> is used
ramp-signal-0 = 󰢿
ramp-signal-1 = 󰢼
ramp-signal-2 = 󰢽
ramp-signal-3 = 󰢽
ramp-signal-4 = 󰢾
ramp-signal-5 = 󰢾

[module/wireless-network]
type = internal/network
interface = wlan0

interval = 3.0

accumulate-stats = false
unknown-as-up = true

; speed-unit = MB

; Available tags:
;   <label-connected> (default)
;   <ramp-signal>
format-connected = <ramp-signal> <label-connected>

; Available tags:
;   <label-disconnected> (default)
format-disconnected = <label-disconnected>

; All labels support the following tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %netspeed%  [wireless+wired] (%upspeed% + %downspeed%) (New in version 3.6.0)
;   %linkspeed% [wired]
;   %mac%       [wireless+wired] (New in version 3.6.0)

; Default: %ifname% %local_ip%
label-connected = %local_ip%  :  %upspeed:0% %downspeed:0%
label-connected-foreground = #eefafa

; Default: (none)
label-disconnected = ''
label-disconnected-foreground = #66ffff

; Default: (none)
;label-packetloss = %essid%
;label-packetloss-foreground = #eefafafa

; Only applies if <ramp-signal> is used
ramp-signal-0 = 󰢿
ramp-signal-1 = 󰢼
ramp-signal-2 = 󰢽
ramp-signal-3 = 󰢽
ramp-signal-4 = 󰢾
ramp-signal-5 = 󰢾

[module/padding]
type = custom/text

format = "  "

[module/power-profile]
type = custom/script

interval = 0

format-prefix = "󰈐 "
format = <label>

exec = $HOME/.local/scripts/get_active_profile.sh
click-left = "asusctl profile -n ; $HOME/.local/scripts/get_active_profile.sh"

[module/battery]
type = internal/battery

full-at = 99
low-at = 10

interval = 30

battery = BAT0
adapter = ADP1

time-format = %H:%M

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity>  <label-discharging>
format-low = <label-low> <animation-low>

label-charging = Charging %percentage%%
label-discharging = %percentage%% - %time%
label-full =   Overflowing ...
label-low = 󰂃 Need Juice

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

bar-capacity-width = 10

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 

animation-charging-framerate = 750

animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 

animation-discharging-framerate = 500

animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200
