
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█


# See https://wiki.hyprland.org/Configuring/Monitors/

# monitor = ,preferred,auto,auto
monitor = HDMI-A-1, 800x600@60, 0x0, 1, bitdepth, 10

# █▀▄▀█ █ █▀ █▀▀
# █░▀░█ █ ▄█ █▄▄


# See https://wiki.hyprland.org/Configuring/Variables/ for more

misc {
    vrr = 0
}

